# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapNeigh' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
    # Pods for MapNeigh
  pod 'SwifterSwift'            # All Extensions
  pod 'CameraManager', '~> 4.0'
  pod 'Firebase/Core'

end
